pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = 'docker-hub-credentials' // Substitua com o ID da credencial no Jenkins
        IMAGE_NAME = '{{your_docker_hub_username}}/{{given image name}}'
    }

    stages {
        stage('Clean up') {
            steps {
                deleteDir() 
            }
        }

        stage('Clone repository') {
            steps {
                git 'https://github.com/{{username}}/simple-java-maven-app.git' 
            }
        }

        stage('Build') {
            steps {
                sh 'mvn clean install' 
            }
        }

        stage('Test') {
            steps {
                sh 'mvn test' 
            }
        }

        stage('Docker Build') {
            steps {
                script {
                    docker.build("${IMAGE_NAME}")
                }
            }
        }

        stage('Docker Push') {
            steps {
                script {
                    docker.withRegistry('', "${DOCKERHUB_CREDENTIALS}") {
                        docker.image("${IMAGE_NAME}").push("latest")
                    }
                }
            }
        }
    }

    post {
        always {
            junit '**/target/surefire-reports/*.xml' // Tests Report
            archiveArtifacts artifacts: '**/target/*.jar', fingerprint: true // Arquivar o JAR
        }
        success {
            echo 'Deployment completed successfully on Docker Hub!'
        }
        failure {
            echo 'The deployment failed. Check the logs.'
        }
    }
}
