pipeline {
    agent any

    parameters {
        booleanParam(defaultValue:false, description: "Enable service?", name: "myBoolean")
        //string(defaultValue:"TEST", description: "Which environment to deploy in?", name: "deployEnv")
        //choice(choices:["TEST", "DEV", "QA", "PRE-PROD", "PROD"], description: "Which environment to deploy in?", name: "deployEnv")
    }

    stages {
        stage("Demo") {
            steps {
                echo "booleanParam is set to: ${params.myBoolean}" //string interpolatioons to replace myBoolean
                //echo "string is set to: ${params.deployEnv}" //string interpolatioons to replace deployEnv
            }
        }
    }
}